UPDATE products SET retail_price = 3.4 WHERE name = 'جلبة لحام 1/2 (20مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 3.4 WHERE name = 'جلبة لحام 1/2 (20مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 3.4;
UPDATE products SET retail_price = 3.94 WHERE name = 'جلبة لحام 3/4 (25مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 3.94 WHERE name = 'جلبة لحام 3/4 (25مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 3.94;
UPDATE products SET retail_price = 5.41 WHERE name = 'جلبة لحام 1 (32مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 5.41 WHERE name = 'جلبة لحام 1 (32مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 5.41;
UPDATE products SET retail_price = 19.69 WHERE name = 'جلبة لحام 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 19.69 WHERE name = 'جلبة لحام 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 19.69;
UPDATE products SET retail_price = 32.81 WHERE name = 'جلبة لحام 2 (62مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 32.81 WHERE name = 'جلبة لحام 2 (62مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 32.81;
UPDATE products SET retail_price = 7.1 WHERE name = 'تي لحام 1/2 (20مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 7.1 WHERE name = 'تي لحام 1/2 (20مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 7.1;
UPDATE products SET retail_price = 8.42 WHERE name = 'تي لحام 3/4 (25مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 8.42 WHERE name = 'تي لحام 3/4 (25مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 8.42;
UPDATE products SET retail_price = 16.84 WHERE name = 'تي لحام 1 (32مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 16.84 WHERE name = 'تي لحام 1 (32مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 16.84;
UPDATE products SET retail_price = 40.47 WHERE name = 'تي لحام 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 40.47 WHERE name = 'تي لحام 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 40.47;
UPDATE products SET retail_price = 78.75 WHERE name = 'تي لحام 2 (62مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 78.75 WHERE name = 'تي لحام 2 (62مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 78.75;
UPDATE products SET retail_price = 3.94 WHERE name = 'كوع لحام 45 1/2 (20مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 3.94 WHERE name = 'كوع لحام 45 1/2 (20مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 3.94;
UPDATE products SET retail_price = 6.56 WHERE name = 'كوع لحام 45 3/4 (25مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 6.56 WHERE name = 'كوع لحام 45 3/4 (25مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 6.56;
UPDATE products SET retail_price = 10.94 WHERE name = 'كوع لحام 45 1 (32مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 10.94 WHERE name = 'كوع لحام 45 1 (32مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 10.94;
UPDATE products SET retail_price = 30.54 WHERE name = 'كوع لحام 45 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 30.54 WHERE name = 'كوع لحام 45 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 30.54;
UPDATE products SET retail_price = 62.33 WHERE name = 'كوع لحام 45 2 (62مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 62.33 WHERE name = 'كوع لحام 45 2 (62مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 62.33;
UPDATE products SET retail_price = 28.88 WHERE name = 'جلبة أنثى 1/2 (20مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 28.88 WHERE name = 'جلبة أنثى 1/2 (20مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 28.88;
UPDATE products SET retail_price = 31.5 WHERE name = 'جلبة أنثى 3/4 * 1/2' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 31.5 WHERE name = 'جلبة أنثى 3/4 * 1/2' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 31.5;
UPDATE products SET retail_price = 35.44 WHERE name = 'جلبة أنثى 3/4 (25مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 35.44 WHERE name = 'جلبة أنثى 3/4 (25مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 35.44;
UPDATE products SET retail_price = 49.44 WHERE name = 'جلبة أنثى 1 (32مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 49.44 WHERE name = 'جلبة أنثى 1 (32مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 49.44;
UPDATE products SET retail_price = 129.06 WHERE name = 'جلبة أنثى 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 129.06 WHERE name = 'جلبة أنثى 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 129.06;
UPDATE products SET retail_price = 192.5 WHERE name = 'جلبة أنثى 2 (62مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 192.5 WHERE name = 'جلبة أنثى 2 (62مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 192.5;
UPDATE products SET retail_price = 32.81 WHERE name = 'تي بسن 1/2 (20مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 32.81 WHERE name = 'تي بسن 1/2 (20مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 32.81;
UPDATE products SET retail_price = 43.75 WHERE name = 'تي بسن 3/4 * 1/2' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 43.75 WHERE name = 'تي بسن 3/4 * 1/2' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 43.75;
UPDATE products SET retail_price = 42.65 WHERE name = 'تي بسن 3/4 (25مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 42.65 WHERE name = 'تي بسن 3/4 (25مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 42.65;
UPDATE products SET retail_price = 59.61 WHERE name = 'تي بسن 1 (32مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 59.61 WHERE name = 'تي بسن 1 (32مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 59.61;
UPDATE products SET retail_price = 179.38 WHERE name = 'تي بسن 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 179.38 WHERE name = 'تي بسن 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 179.38;
UPDATE products SET retail_price = 31.17 WHERE name = 'كوع بسن 1/2 (20مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 31.17 WHERE name = 'كوع بسن 1/2 (20مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 31.17;
UPDATE products SET retail_price = 43.75 WHERE name = 'كوع بسن 3/4 * 1/2' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 43.75 WHERE name = 'كوع بسن 3/4 * 1/2' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 43.75;
UPDATE products SET retail_price = 48.12 WHERE name = 'كوع بسن 3/4 (25مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 48.12 WHERE name = 'كوع بسن 3/4 (25مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 48.12;
UPDATE products SET retail_price = 61.25 WHERE name = 'كوع بسن 1 (32مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 61.25 WHERE name = 'كوع بسن 1 (32مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 61.25;
UPDATE products SET retail_price = 10.94 WHERE name = 'كوع مفتوح 3/4 (25مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 10.94 WHERE name = 'كوع مفتوح 3/4 (25مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 10.94;
UPDATE products SET retail_price = 19.69 WHERE name = 'طبة اختبار 1 (32مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 19.69 WHERE name = 'طبة اختبار 1 (32مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 19.69;
UPDATE products SET retail_price = 12.15 WHERE name = 'تي مسلوب 1/2 * 3/4 (25*20)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 12.15 WHERE name = 'تي مسلوب 1/2 * 3/4 (25*20)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 12.15;
UPDATE products SET retail_price = 20.69 WHERE name = 'تي مسلوب 1 * 3/4 (32*25)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 20.69 WHERE name = 'تي مسلوب 1 * 3/4 (32*25)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 20.69;
UPDATE products SET retail_price = 65.62 WHERE name = 'تي مسلوب 1 1/2 * 1/2 (50*20)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 65.62 WHERE name = 'تي مسلوب 1 1/2 * 1/2 (50*20)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 65.62;
UPDATE products SET retail_price = 49.22 WHERE name = 'تي مسلوب 1 1/2 * 3/4 (50*25)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 49.22 WHERE name = 'تي مسلوب 1 1/2 * 3/4 (50*25)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 49.22;
UPDATE products SET retail_price = 50.31 WHERE name = 'تي مسلوب 1 1/2 * 1 (50*32)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 50.31 WHERE name = 'تي مسلوب 1 1/2 * 1 (50*32)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 50.31;
UPDATE products SET retail_price = 98.44 WHERE name = 'تي مسلوب 2 * 1/2 (62*20)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 98.44 WHERE name = 'تي مسلوب 2 * 1/2 (62*20)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 98.44;
UPDATE products SET retail_price = 98.44 WHERE name = 'تي مسلوب 2 * 3/4 (62*25)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 98.44 WHERE name = 'تي مسلوب 2 * 3/4 (62*25)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 98.44;
UPDATE products SET retail_price = 87.5 WHERE name = 'تي مسلوب 2 * 1 (62*32)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 87.5 WHERE name = 'تي مسلوب 2 * 1 (62*32)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 87.5;
UPDATE products SET retail_price = 91.88 WHERE name = 'تي مسلوب 2 * 1 1/2 (62*50)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 91.88 WHERE name = 'تي مسلوب 2 * 1 1/2 (62*50)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 91.88;
UPDATE products SET retail_price = 7.66 WHERE name = 'جلبة مسلوب 1 * 3/4 (32*25)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 7.66 WHERE name = 'جلبة مسلوب 1 * 3/4 (32*25)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 7.66;
UPDATE products SET retail_price = 26.25 WHERE name = 'جلبة مسلوب 1 1/2 * 1/2 (50*20)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 26.25 WHERE name = 'جلبة مسلوب 1 1/2 * 1/2 (50*20)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 26.25;
UPDATE products SET retail_price = 15.75 WHERE name = 'جلبة مسلوب 1 1/2 * 3/4 (50*25)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 15.75 WHERE name = 'جلبة مسلوب 1 1/2 * 3/4 (50*25)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 15.75;
UPDATE products SET retail_price = 40.47 WHERE name = 'جلبة مسلوب 2 * 1/2 (62*20)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 40.47 WHERE name = 'جلبة مسلوب 2 * 1/2 (62*20)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 40.47;
UPDATE products SET retail_price = 30.62 WHERE name = 'جلبة مسلوب 2 * 3/4 (62*25)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 30.62 WHERE name = 'جلبة مسلوب 2 * 3/4 (62*25)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 30.62;
UPDATE products SET retail_price = 30.62 WHERE name = 'جلبة مسلوب 2 * 1 (62*32)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 30.62 WHERE name = 'جلبة مسلوب 2 * 1 (62*32)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 30.62;
UPDATE products SET retail_price = 32.81 WHERE name = 'جلبة مسلوب 2 * 1 1/2 (62*50)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 32.81 WHERE name = 'جلبة مسلوب 2 * 1 1/2 (62*50)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 32.81;
UPDATE products SET retail_price = 32.81 WHERE name = 'جلبة ذكر 1/2 * 3/4 (25*20)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 32.81 WHERE name = 'جلبة ذكر 1/2 * 3/4 (25*20)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 32.81;
UPDATE products SET retail_price = 36.75 WHERE name = 'جلبة ذكر 1 * 1/2 (32*20)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 36.75 WHERE name = 'جلبة ذكر 1 * 1/2 (32*20)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 36.75;
UPDATE products SET retail_price = 42.0 WHERE name = 'جلبة ذكر 1 * 3/4 (32*25)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 42.0 WHERE name = 'جلبة ذكر 1 * 3/4 (32*25)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 42.0;
UPDATE products SET retail_price = 48.56 WHERE name = 'جلبة ذكر 1 1/2 * 1/2 (50*20)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 48.56 WHERE name = 'جلبة ذكر 1 1/2 * 1/2 (50*20)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 48.56;
UPDATE products SET retail_price = 63.44 WHERE name = 'جلبة ذكر 1 1/2 * 3/4 (50*25)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 63.44 WHERE name = 'جلبة ذكر 1 1/2 * 3/4 (50*25)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 63.44;
UPDATE products SET retail_price = 144.38 WHERE name = 'جلبة ذكر 1 1/2 * 1 (50*32)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 144.38 WHERE name = 'جلبة ذكر 1 1/2 * 1 (50*32)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 144.38;
UPDATE products SET retail_price = 218.75 WHERE name = 'جلبة ذكر 2 * 1/2 (62*20)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 218.75 WHERE name = 'جلبة ذكر 2 * 1/2 (62*20)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 218.75;
UPDATE products SET retail_price = 13.77 WHERE name = 'كرنك حقن ثقيل 1/2 (20مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 13.77 WHERE name = 'كرنك حقن ثقيل 1/2 (20مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 13.77;
UPDATE products SET retail_price = 20.56 WHERE name = 'كرنك حقن ثقيل 3/4 (25مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 20.56 WHERE name = 'كرنك حقن ثقيل 3/4 (25مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 20.56;
UPDATE products SET retail_price = 3.28 WHERE name = 'طبة كاب 1/2 (20مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 3.28 WHERE name = 'طبة كاب 1/2 (20مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 3.28;
UPDATE products SET retail_price = 4.92 WHERE name = 'طبة كاب 3/4 (25مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 4.92 WHERE name = 'طبة كاب 3/4 (25مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 4.92;
UPDATE products SET retail_price = 7.12 WHERE name = 'طبة كاب 1 (32مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 7.12 WHERE name = 'طبة كاب 1 (32مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 7.12;
UPDATE products SET retail_price = 21.09 WHERE name = 'طبة كاب 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 21.09 WHERE name = 'طبة كاب 1 1/2 (50مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 21.09;
UPDATE products SET retail_price = 37.19 WHERE name = 'طبة كاب 2 (62مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 37.19 WHERE name = 'طبة كاب 2 (62مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 37.19;
UPDATE products SET retail_price = 301.91 WHERE name = 'محبس دفع 1/2 (20مم)' AND company = 'روك بولي' AND retail_price = 0;
UPDATE products SET retail_price = 301.91 WHERE name = 'محبس دفع 1/2 (20مم)' AND company = 'روك بولي' AND retail_price != 0 AND retail_price < 301.91;
UPDATE products SET retail_price = 9.0 WHERE name = 'كوع عادي 3/4' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 9.0 WHERE name = 'كوع عادي 3/4' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 9.0;
UPDATE products SET retail_price = 13.0 WHERE name = 'كوع عادي 1' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 13.0 WHERE name = 'كوع عادي 1' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 13.0;
UPDATE products SET retail_price = 18.0 WHERE name = 'كوع عادي 1 1/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 18.0 WHERE name = 'كوع عادي 1 1/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 18.0;
UPDATE products SET retail_price = 40.0 WHERE name = 'كوع عادي 2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 40.0 WHERE name = 'كوع عادي 2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 40.0;
UPDATE products SET retail_price = 66.0 WHERE name = 'كوع عادي 75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 66.0 WHERE name = 'كوع عادي 75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 66.0;
UPDATE products SET retail_price = 160.0 WHERE name = 'كوع عادي 110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 160.0 WHERE name = 'كوع عادي 110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 160.0;
UPDATE products SET retail_price = 31.0 WHERE name = 'كوع باب 1 1/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 31.0 WHERE name = 'كوع باب 1 1/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 31.0;
UPDATE products SET retail_price = 62.0 WHERE name = 'كوع باب 2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 62.0 WHERE name = 'كوع باب 2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 62.0;
UPDATE products SET retail_price = 84.0 WHERE name = 'كوع باب 75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 84.0 WHERE name = 'كوع باب 75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 84.0;
UPDATE products SET retail_price = 220.0 WHERE name = 'كوع باب 110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 220.0 WHERE name = 'كوع باب 110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 220.0;
UPDATE products SET retail_price = 9.0 WHERE name = 'كوع مفتوح 3/4' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 9.0 WHERE name = 'كوع مفتوح 3/4' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 9.0;
UPDATE products SET retail_price = 13.0 WHERE name = 'كوع مفتوح 1' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 13.0 WHERE name = 'كوع مفتوح 1' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 13.0;
UPDATE products SET retail_price = 18.0 WHERE name = 'كوع مفتوح 1 1/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 18.0 WHERE name = 'كوع مفتوح 1 1/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 18.0;
UPDATE products SET retail_price = 40.0 WHERE name = 'كوع مفتوح 2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 40.0 WHERE name = 'كوع مفتوح 2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 40.0;
UPDATE products SET retail_price = 66.0 WHERE name = 'كوع مفتوح 75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 66.0 WHERE name = 'كوع مفتوح 75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 66.0;
UPDATE products SET retail_price = 186.0 WHERE name = 'كوع مفتوح 110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 186.0 WHERE name = 'كوع مفتوح 110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 186.0;
UPDATE products SET retail_price = 160.0 WHERE name = 'كوع مفتوح 160' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 160.0 WHERE name = 'كوع مفتوح 160' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 160.0;
UPDATE products SET retail_price = 19.0 WHERE name = 'مشترك واي 1' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 19.0 WHERE name = 'مشترك واي 1' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 19.0;
UPDATE products SET retail_price = 53.0 WHERE name = 'مشترك مسلوب 2*11/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 53.0 WHERE name = 'مشترك مسلوب 2*11/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 53.0;
UPDATE products SET retail_price = 30.0 WHERE name = 'مشترك واي 1 1/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 30.0 WHERE name = 'مشترك واي 1 1/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 30.0;
UPDATE products SET retail_price = 53.0 WHERE name = 'مشترك مسلوب 2*2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 53.0 WHERE name = 'مشترك مسلوب 2*2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 53.0;
UPDATE products SET retail_price = 42.0 WHERE name = 'مشترك واي 2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 42.0 WHERE name = 'مشترك واي 2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 42.0;
UPDATE products SET retail_price = 84.0 WHERE name = 'مشترك مسلوب 75*11/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 84.0 WHERE name = 'مشترك مسلوب 75*11/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 84.0;
UPDATE products SET retail_price = 84.0 WHERE name = 'مشترك واي 75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 84.0 WHERE name = 'مشترك واي 75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 84.0;
UPDATE products SET retail_price = 88.0 WHERE name = 'مشترك مسلوب 75*2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 88.0 WHERE name = 'مشترك مسلوب 75*2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 88.0;
UPDATE products SET retail_price = 134.0 WHERE name = 'مشترك واي 110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 134.0 WHERE name = 'مشترك واي 110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 134.0;
UPDATE products SET retail_price = 60.7 WHERE name = 'مشترك مسلوب 110/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 60.7 WHERE name = 'مشترك مسلوب 110/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 60.7;
UPDATE products SET retail_price = 400.0 WHERE name = 'مشترك واي 110/160' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 400.0 WHERE name = 'مشترك واي 110/160' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 400.0;
UPDATE products SET retail_price = 108.0 WHERE name = 'مشترك مسلوب 110/75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 108.0 WHERE name = 'مشترك مسلوب 110/75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 108.0;
UPDATE products SET retail_price = 312.0 WHERE name = 'مشترك واي 160' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 312.0 WHERE name = 'مشترك واي 160' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 312.0;
UPDATE products SET retail_price = 7.2 WHERE name = 'جلبة لحام 3/4' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 7.2 WHERE name = 'جلبة لحام 3/4' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 7.2;
UPDATE products SET retail_price = 8.0 WHERE name = 'جلبة لحام 1' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 8.0 WHERE name = 'جلبة لحام 1' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 8.0;
UPDATE products SET retail_price = 10.9 WHERE name = 'جلبة لحام 1 1/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 10.9 WHERE name = 'جلبة لحام 1 1/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 10.9;
UPDATE products SET retail_price = 14.4 WHERE name = 'جلبة لحام 2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 14.4 WHERE name = 'جلبة لحام 2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 14.4;
UPDATE products SET retail_price = 12.4 WHERE name = 'بوش 2*11/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 12.4 WHERE name = 'بوش 2*11/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 12.4;
UPDATE products SET retail_price = 26.0 WHERE name = 'جلبة لحام 75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 26.0 WHERE name = 'جلبة لحام 75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 26.0;
UPDATE products SET retail_price = 21.0 WHERE name = 'بوش 75*11/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 21.0 WHERE name = 'بوش 75*11/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 21.0;
UPDATE products SET retail_price = 42.5 WHERE name = 'تابع بوش 110*2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 42.5 WHERE name = 'تابع بوش 110*2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 42.5;
UPDATE products SET retail_price = 40.0 WHERE name = 'جلبة لحام 110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 40.0 WHERE name = 'جلبة لحام 110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 40.0;
UPDATE products SET retail_price = 21.0 WHERE name = 'بوش 75*2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 21.0 WHERE name = 'بوش 75*2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 21.0;
UPDATE products SET retail_price = 42.5 WHERE name = 'تابع بوش 110*75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 42.5 WHERE name = 'تابع بوش 110*75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 42.5;
UPDATE products SET retail_price = 88.0 WHERE name = 'جلبة لحام 160' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 88.0 WHERE name = 'جلبة لحام 160' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 88.0;
UPDATE products SET retail_price = 42.5 WHERE name = 'بوش 110*11/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 42.5 WHERE name = 'بوش 110*11/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 42.5;
UPDATE products SET retail_price = 88.0 WHERE name = 'تابع بوش 160/110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 88.0 WHERE name = 'تابع بوش 160/110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 88.0;
UPDATE products SET retail_price = 78.0 WHERE name = 'بيبة عاليه سوبر 2*11/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 78.0 WHERE name = 'بيبة عاليه سوبر 2*11/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 78.0;
UPDATE products SET retail_price = 80.0 WHERE name = 'بيبة عاليه سوبر 2*2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 80.0 WHERE name = 'بيبة عاليه سوبر 2*2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 80.0;
UPDATE products SET retail_price = 16.0 WHERE name = 'بيبه اسم 3/4' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 16.0 WHERE name = 'بيبه اسم 3/4' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 16.0;
UPDATE products SET retail_price = 24.0 WHERE name = 'بيبه اسم 1' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 24.0 WHERE name = 'بيبه اسم 1' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 24.0;
UPDATE products SET retail_price = 32.0 WHERE name = 'هوايه 1 1/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 32.0 WHERE name = 'هوايه 1 1/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 32.0;
UPDATE products SET retail_price = 22.5 WHERE name = 'هوايه 2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 22.5 WHERE name = 'هوايه 2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 22.5;
UPDATE products SET retail_price = 28.0 WHERE name = 'هوايه 75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 28.0 WHERE name = 'هوايه 75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 28.0;
UPDATE products SET retail_price = 40.0 WHERE name = 'هوايه 110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 40.0 WHERE name = 'هوايه 110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 40.0;
UPDATE products SET retail_price = 76.0 WHERE name = 'سيفون 75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 76.0 WHERE name = 'سيفون 75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 76.0;
UPDATE products SET retail_price = 108.0 WHERE name = 'سيفون 110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 108.0 WHERE name = 'سيفون 110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 108.0;
UPDATE products SET retail_price = 312.0 WHERE name = 'سيفون 160' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 312.0 WHERE name = 'سيفون 160' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 312.0;
UPDATE products SET retail_price = 35.0 WHERE name = 'طبة تسليك 75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 35.0 WHERE name = 'طبة تسليك 75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 35.0;
UPDATE products SET retail_price = 51.3 WHERE name = 'طبة تسليك 110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 51.3 WHERE name = 'طبة تسليك 110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 51.3;
UPDATE products SET retail_price = 80.0 WHERE name = 'صليبه 75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 80.0 WHERE name = 'صليبه 75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 80.0;
UPDATE products SET retail_price = 130.0 WHERE name = 'صليبه 110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 130.0 WHERE name = 'صليبه 110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 130.0;
UPDATE products SET retail_price = 64.0 WHERE name = 'جلبة اصلاح 75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 64.0 WHERE name = 'جلبة اصلاح 75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 64.0;
UPDATE products SET retail_price = 138.0 WHERE name = 'جلبة اصلاح 110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 138.0 WHERE name = 'جلبة اصلاح 110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 138.0;
UPDATE products SET retail_price = 260.0 WHERE name = 'جلبة اصلاح 160/110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 260.0 WHERE name = 'جلبة اصلاح 160/110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 260.0;
UPDATE products SET retail_price = 5.5 WHERE name = 'رقبه بيبه' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 5.5 WHERE name = 'رقبه بيبه' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 5.5;
UPDATE products SET retail_price = 13.0 WHERE name = 'طبة كاب 1 1/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 13.0 WHERE name = 'طبة كاب 1 1/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 13.0;
UPDATE products SET retail_price = 5.5 WHERE name = 'طبة كاب 2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 5.5 WHERE name = 'طبة كاب 2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 5.5;
UPDATE products SET retail_price = 14.0 WHERE name = 'طبه بيبه 2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 14.0 WHERE name = 'طبه بيبه 2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 14.0;
UPDATE products SET retail_price = 27.5 WHERE name = 'طبة كاب 75' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 27.5 WHERE name = 'طبة كاب 75' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 27.5;
UPDATE products SET retail_price = 26.0 WHERE name = 'طبة كاب 110' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 26.0 WHERE name = 'طبة كاب 110' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 26.0;
UPDATE products SET retail_price = 21.0 WHERE name = 'جلبة بسن 1 1/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 21.0 WHERE name = 'جلبة بسن 1 1/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 21.0;
UPDATE products SET retail_price = 26.0 WHERE name = 'كوع بسن 1 1/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 26.0 WHERE name = 'كوع بسن 1 1/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 26.0;
UPDATE products SET retail_price = 40.0 WHERE name = 'جلبة بسن 2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 40.0 WHERE name = 'جلبة بسن 2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 40.0;
UPDATE products SET retail_price = 40.0 WHERE name = 'كوع بسن 2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 40.0 WHERE name = 'كوع بسن 2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 40.0;
UPDATE products SET retail_price = 230.0 WHERE name = 'جلبة بسن 2*1 1/2' AND company = 'روك 110' AND retail_price = 0;
UPDATE products SET retail_price = 230.0 WHERE name = 'جلبة بسن 2*1 1/2' AND company = 'روك 110' AND retail_price != 0 AND retail_price < 230.0;
UPDATE products SET retail_price = 7.2 WHERE name = 'كوع عاده 3/4' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 7.2 WHERE name = 'كوع عاده 3/4' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 7.2;
UPDATE products SET retail_price = 9.0 WHERE name = 'كوع عاده 1' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 9.0 WHERE name = 'كوع عاده 1' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 9.0;
UPDATE products SET retail_price = 9.0 WHERE name = 'كوع باب 1' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 9.0 WHERE name = 'كوع باب 1' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 9.0;
UPDATE products SET retail_price = 13.0 WHERE name = 'كوع عاده 1 1/2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 13.0 WHERE name = 'كوع عاده 1 1/2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 13.0;
UPDATE products SET retail_price = 13.0 WHERE name = 'كوع باب 1 1/2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 13.0 WHERE name = 'كوع باب 1 1/2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 13.0;
UPDATE products SET retail_price = 18.0 WHERE name = 'كوع عاده 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 18.0 WHERE name = 'كوع عاده 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 18.0;
UPDATE products SET retail_price = 31.0 WHERE name = 'كوع باب 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 31.0 WHERE name = 'كوع باب 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 31.0;
UPDATE products SET retail_price = 34.0 WHERE name = 'كوع عاده 48' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 34.0 WHERE name = 'كوع عاده 48' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 34.0;
UPDATE products SET retail_price = 48.0 WHERE name = 'كوع عاده 90' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 48.0 WHERE name = 'كوع عاده 90' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 48.0;
UPDATE products SET retail_price = 114.0 WHERE name = 'كوع باب 90' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 114.0 WHERE name = 'كوع باب 90' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 114.0;
UPDATE products SET retail_price = 66.0 WHERE name = 'كوع عاده 114' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 66.0 WHERE name = 'كوع عاده 114' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 66.0;
UPDATE products SET retail_price = 88.0 WHERE name = 'كوع باب 114' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 88.0 WHERE name = 'كوع باب 114' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 88.0;
UPDATE products SET retail_price = 186.0 WHERE name = 'كوع عاده 168' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 186.0 WHERE name = 'كوع عاده 168' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 186.0;
UPDATE products SET retail_price = 220.0 WHERE name = 'كوع باب 168' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 220.0 WHERE name = 'كوع باب 168' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 220.0;
UPDATE products SET retail_price = 8.0 WHERE name = 'كوع مفتوح 3/4' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 8.0 WHERE name = 'كوع مفتوح 3/4' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 8.0;
UPDATE products SET retail_price = 19.0 WHERE name = 'مشترك واي 3/4' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 19.0 WHERE name = 'مشترك واي 3/4' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 19.0;
UPDATE products SET retail_price = 1.0 WHERE name = 'جلبة لحام 3/4' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 1.0 WHERE name = 'جلبة لحام 3/4' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 1.0;
UPDATE products SET retail_price = 10.9 WHERE name = 'كوع مفتوح 1' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 10.9 WHERE name = 'كوع مفتوح 1' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 10.9;
UPDATE products SET retail_price = 30.0 WHERE name = 'مشترك واي 1' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 30.0 WHERE name = 'مشترك واي 1' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 30.0;
UPDATE products SET retail_price = 1.5 WHERE name = 'جلبة لحام 1' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 1.5 WHERE name = 'جلبة لحام 1' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 1.5;
UPDATE products SET retail_price = 14.4 WHERE name = 'كوع مفتوح 1 1/2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 14.4 WHERE name = 'كوع مفتوح 1 1/2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 14.4;
UPDATE products SET retail_price = 42.0 WHERE name = 'مشترك واي 1 1/2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 42.0 WHERE name = 'مشترك واي 1 1/2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 42.0;
UPDATE products SET retail_price = 2.0 WHERE name = 'جلبة لحام 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 2.0 WHERE name = 'جلبة لحام 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 2.0;
UPDATE products SET retail_price = 18.0 WHERE name = 'كوع مفتوح 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 18.0 WHERE name = 'كوع مفتوح 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 18.0;
UPDATE products SET retail_price = 90.0 WHERE name = 'مشترك واي 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 90.0 WHERE name = 'مشترك واي 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 90.0;
UPDATE products SET retail_price = 42.5 WHERE name = 'كوع مفتوح 48' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 42.5 WHERE name = 'كوع مفتوح 48' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 42.5;
UPDATE products SET retail_price = 90.0 WHERE name = 'مشترك واي 48' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 90.0 WHERE name = 'مشترك واي 48' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 90.0;
UPDATE products SET retail_price = 62.0 WHERE name = 'جلبة لحام 48' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 62.0 WHERE name = 'جلبة لحام 48' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 62.0;
UPDATE products SET retail_price = 66.0 WHERE name = 'كوع مفتوح 90' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 66.0 WHERE name = 'كوع مفتوح 90' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 66.0;
UPDATE products SET retail_price = 148.0 WHERE name = 'مشترك واي 90' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 148.0 WHERE name = 'مشترك واي 90' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 148.0;
UPDATE products SET retail_price = 84.0 WHERE name = 'جلبة لحام 90' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 84.0 WHERE name = 'جلبة لحام 90' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 84.0;
UPDATE products SET retail_price = 80.0 WHERE name = 'كوع مفتوح 114' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 80.0 WHERE name = 'كوع مفتوح 114' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 80.0;
UPDATE products SET retail_price = 400.0 WHERE name = 'مشترك واي 168/114' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 400.0 WHERE name = 'مشترك واي 168/114' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 400.0;
UPDATE products SET retail_price = 160.0 WHERE name = 'جلبة لحام 114' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 160.0 WHERE name = 'جلبة لحام 114' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 160.0;
UPDATE products SET retail_price = 168.0 WHERE name = 'كوع مفتوح 168' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 168.0 WHERE name = 'كوع مفتوح 168' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 168.0;
UPDATE products SET retail_price = 312.0 WHERE name = 'مشترك واي 168' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 312.0 WHERE name = 'مشترك واي 168' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 312.0;
UPDATE products SET retail_price = 210.0 WHERE name = 'جلبة لحام 168' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 210.0 WHERE name = 'جلبة لحام 168' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 210.0;
UPDATE products SET retail_price = 16.0 WHERE name = 'مشترك عاده 3/4' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 16.0 WHERE name = 'مشترك عاده 3/4' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 16.0;
UPDATE products SET retail_price = 24.0 WHERE name = 'مشترك عاده 1' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 24.0 WHERE name = 'مشترك عاده 1' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 24.0;
UPDATE products SET retail_price = 48.0 WHERE name = 'مشترك عاده 1 1/2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 48.0 WHERE name = 'مشترك عاده 1 1/2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 48.0;
UPDATE products SET retail_price = 32.0 WHERE name = 'مشترك باب 1 1/2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 32.0 WHERE name = 'مشترك باب 1 1/2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 32.0;
UPDATE products SET retail_price = 80.0 WHERE name = 'مشترك عاده 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 80.0 WHERE name = 'مشترك عاده 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 80.0;
UPDATE products SET retail_price = 66.0 WHERE name = 'مشترك باب 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 66.0 WHERE name = 'مشترك باب 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 66.0;
UPDATE products SET retail_price = 110.0 WHERE name = 'مشترك عاده 90' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 110.0 WHERE name = 'مشترك عاده 90' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 110.0;
UPDATE products SET retail_price = 89.0 WHERE name = 'مشترك باب 90' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 89.0 WHERE name = 'مشترك باب 90' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 89.0;
UPDATE products SET retail_price = 312.0 WHERE name = 'مشترك عاده 114' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 312.0 WHERE name = 'مشترك عاده 114' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 312.0;
UPDATE products SET retail_price = 290.0 WHERE name = 'مشترك باب 114' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 290.0 WHERE name = 'مشترك باب 114' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 290.0;
UPDATE products SET retail_price = 12.4 WHERE name = 'بيبة عالية سوبر 1 1/2 * 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 12.4 WHERE name = 'بيبة عالية سوبر 1 1/2 * 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 12.4;
UPDATE products SET retail_price = 53.0 WHERE name = 'بيبه اسم 2 * 1 1/2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 53.0 WHERE name = 'بيبه اسم 2 * 1 1/2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 53.0;
UPDATE products SET retail_price = 78.0 WHERE name = 'بوش 2 * 1 1/2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 78.0 WHERE name = 'بوش 2 * 1 1/2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 78.0;
UPDATE products SET retail_price = 53.0 WHERE name = 'بيبة عالية سوبر 2 * 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 53.0 WHERE name = 'بيبة عالية سوبر 2 * 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 53.0;
UPDATE products SET retail_price = 80.0 WHERE name = 'بيبه اسم 2 * 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 80.0 WHERE name = 'بيبه اسم 2 * 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 80.0;
UPDATE products SET retail_price = 21.0 WHERE name = 'بوش 90 / 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 21.0 WHERE name = 'بوش 90 / 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 21.0;
UPDATE products SET retail_price = 42.5 WHERE name = 'مشترك مسلوب عاده 90 / 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 42.5 WHERE name = 'مشترك مسلوب عاده 90 / 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 42.5;
UPDATE products SET retail_price = 140.0 WHERE name = 'صليبه 90' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 140.0 WHERE name = 'صليبه 90' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 140.0;
UPDATE products SET retail_price = 80.0 WHERE name = 'جلبة إصلاح 90' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 80.0 WHERE name = 'جلبة إصلاح 90' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 80.0;
UPDATE products SET retail_price = 110.0 WHERE name = 'مشترك مسلوب عاده 114 / 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 110.0 WHERE name = 'مشترك مسلوب عاده 114 / 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 110.0;
UPDATE products SET retail_price = 89.0 WHERE name = 'مشترك مسلوب باب 114 / 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 89.0 WHERE name = 'مشترك مسلوب باب 114 / 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 89.0;
UPDATE products SET retail_price = 168.5 WHERE name = 'صليبه 114' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 168.5 WHERE name = 'صليبه 114' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 168.5;
UPDATE products SET retail_price = 145.0 WHERE name = 'جلبة إصلاح 114' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 145.0 WHERE name = 'جلبة إصلاح 114' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 145.0;
UPDATE products SET retail_price = 230.0 WHERE name = 'مشترك مسلوب عاده 114 / 168' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 230.0 WHERE name = 'مشترك مسلوب عاده 114 / 168' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 230.0;
UPDATE products SET retail_price = 260.0 WHERE name = 'مشترك مسلوب باب 114 / 168' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 260.0 WHERE name = 'مشترك مسلوب باب 114 / 168' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 260.0;
UPDATE products SET retail_price = 13.0 WHERE name = 'طبه كاب 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 13.0 WHERE name = 'طبه كاب 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 13.0;
UPDATE products SET retail_price = 5.5 WHERE name = 'طبه كاب 1 1/2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 5.5 WHERE name = 'طبه كاب 1 1/2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 5.5;
UPDATE products SET retail_price = 5.5 WHERE name = 'طبه كاب 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 5.5 WHERE name = 'طبه كاب 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 5.5;
UPDATE products SET retail_price = 21.0 WHERE name = 'طبه بيبه رقبه بيبه' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 21.0 WHERE name = 'طبه بيبه رقبه بيبه' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 21.0;
UPDATE products SET retail_price = 40.0 WHERE name = 'سيفون 2 * 1 1/2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 40.0 WHERE name = 'سيفون 2 * 1 1/2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 40.0;
UPDATE products SET retail_price = 27.5 WHERE name = 'جلبة بسن / كوع بسن 1 1/2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 27.5 WHERE name = 'جلبة بسن / كوع بسن 1 1/2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 27.5;
UPDATE products SET retail_price = 40.0 WHERE name = 'جلبة بسن / كوع بسن 2' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 40.0 WHERE name = 'جلبة بسن / كوع بسن 2' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 40.0;
UPDATE products SET retail_price = 140.0 WHERE name = 'جلبه اصلاح 114' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 140.0 WHERE name = 'جلبه اصلاح 114' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 140.0;
UPDATE products SET retail_price = 26.0 WHERE name = 'جلبه اصلاح ماسوره 114' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 26.0 WHERE name = 'جلبه اصلاح ماسوره 114' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 26.0;
UPDATE products SET retail_price = 63.2 WHERE name = 'جلبه اصلاح' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 63.2 WHERE name = 'جلبه اصلاح' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 63.2;
UPDATE products SET retail_price = 63.2 WHERE name = 'مشترك' AND company = 'روك 114' AND retail_price = 0;
UPDATE products SET retail_price = 63.2 WHERE name = 'مشترك' AND company = 'روك 114' AND retail_price != 0 AND retail_price < 63.2;
SELECT 'Done' as status;